version: "3"
services:
  mongo:
    image: "mongo:latest"
    ports: 
      - "27017:27017"
  customerservice:
    build:
      dockerfile: Dockerfile
      context: .
    image: workshop3:1.0
    environment:
      - CUSTOMER_SVC_PORT=3000
      - CUSTOMER_DB_URL=mongodb://mongo:27017/customer-db
    links:
      - mongo